### ISSUE TITLE
Allow configuration to be saved

### ISSUE THREAD

**Issue by MarcelGarus** [Zortax/hpi-vpn#1]
It would make sense to allow saving a user's username/password combination, i.e. in some file at `~/.hpiconfig` or something like that - just like `git` lets you store your credentials in `~/.gitconfig`.

From a privacy perspective, I don't see that many concerns as the file could be accessible only to the current user.

**Comment by zortax** [comment]
It is never a good idea to store passwords in plain text. The password would need to be saved in the os keychain. As different linux distros use different keychains, this feature won't be a lot of fun to implement, anyway, feel free to open a pull request.
(Actually, git does not store HTTP credentials by default. On macOS and Windows Git is able to utilize the plattform's keychain to store the password encrypted. On linux you _can_ tell Git to store your password in plain tex, however, this is not recommended. Just use a SSH key :P)

**Comment by MarcelGarus** [comment]
Oh, I see. You're right of course.
I'll close this issue then.

**Comment by zortax** [comment]
@marcelgarus it was a good idea, but I'm just not motivated enough to implement that keychain mess
